### ISSUE TITLE
Global Default settings, and the ability to edit them

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#17]
After meeting with Patricia, Jennie, and CJ...

We should make these the defaults, and have them all be editable form one place on the settings panel.  Its almost always Patricia, unless she is out of town, then Jennie will need to be able to swap herself in then back out, ideally in one place.

Can we have these defaults set, and have UI on settings for changing it?

 - From Name - Patricia Janeway
 - Reply-to - pjaneway@dzs.org
 - Contact Name - Patricia Janeway
 - Contact Phone - 248.336.5757
 - Contact Email - pjaneway@dzs.org

Thought: the from-name and reply-to will almost certainly match contact-name and contact-email.  To people other than us developer-types, this is confusing.  Can we just have them be the same?  Just use 'Contact-'.?

**Comment by d4mation** [comment]
They can certainly be the same, but I figure "From Name" may want to be kept a separate field. That way it can be something immediately recognizable like "Detroit Zoological Society" (which will show prominently in the Recipients Inbox) while the Contact Name can be Patricia Janeway which only shows within the e-mail's contents.

The Contact Name is used in the Template for the e-mail while the From Name is used for the Email itself.

I agree it can seem kind of confusing, but I feel like there's a very large distinction in what they are used for. Maybe we can instead set "Contact Name" to use the "From Name" if nothing is set, similar to how "Contact Email" uses the "Reply To" if nothing is set?

![image](https://cloud.githubusercontent.com/assets/7770631/18758159/e5bffdac-80c4-11e6-8ba6-4184f2926522.png)

(As an unrelated sidenote, I love the "Meet Your Friend at the Zoo" day. Got one of the best dogs I ever had when I was a kid on that day).

**Comment by thisisjoewells** [comment]
Ha ha.  Good points.  Indeed, I got them confused for a second here...

I guess we should do this?

Label 'from name' as 'Organization Name (from name)'.  And of course have it default to 'Detroit Zoological Society'.

Then have the 3 main ones that Jennie would occasionally have to change to herself:
Contact Name
Contact Email
Contact Phone

Then have reply to have extra information:

Default Reply-To Email Address - leave blank and it will be set to contact name, or if for some reason you want it to be different enter it here.

What do you think?

I'm glad to hear that you got a dog and love MYBF at the Zoo day.  The Event staff have fun that day with all the dogs.

**Comment by d4mation** [comment]
Currently the form is set to go the opposite direction, actually:

- Default/Global Reply-To gets set on the main Settings Page
- This can be overridden for each Campaign Form Submission
- The Contact Email can be set manually, or it will default to the Reply-To Field (From this form or then fall back further to the Global Setting if none is set)

I think that logically it flows better that way (at least in the code), since the Reply-To Field is required by MailChimp to process an API Request. The Contact Email is technically only in use within the Email Content.

**Comment by d4mation** [comment]
I also set up `Contact Name` to work the same way in relation to `Organization Name ("From:" Name)` just now. It is on the `minor-display-adjustments` branch as it made most sense to take care of that while moving things around.

**Comment by thisisjoewells** [comment]
I'm having trouble loading up the 'minor-display-adjustments' branch.  But I think I am seeing everything on 'Develop'?

This all sounds good.

**Comment by d4mation** [comment]
Yeah, I ended up moving everything to Master since most of the Issues depended on each other and testing each individual one without the others present I was afraid would be very confusing for the both of us.
