### ISSUE TITLE
Random - They don't want to call them 'Press Releases' anymore.

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#21]
Let me double-check and get clarity on this.  But at the meeting they said they want to move to calling them 'Media Releases'.

I realize this will need a corresponding issue in the CPT-Press Release Repo.

I'll make that once I confirm and they understand the implications.  Nothing too major.

**Comment by d4mation** [comment]
I don't think this should cause a lot of problems.

The only problem I can think of would be for permalinks. They would probably want to change the URL structure, which could break any hardlinks to a Press Release that are embedded into another Post somewhere or possibly in an E-Mail somewhere. 

We could potentially put in a redirect pattern to catch any of those though.

Everything else is pretty much visual. The Post Type name of `press-release` could stay that way so it doesn't affect any other references to it (like in this plugin) and we'd still be able to change its URL structure and the Labels on the Backend.

**Comment by thisisjoewells** [comment]
We have decided, for now, not to change the nomenclature.
