### ISSUE TITLE
Tweak the labels and order of the 4 columns

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#22]
We agreed on some tweaks to make it fit their use-case and daily workflow.

Change order and labels of the 4 columns/email types:

1: Test/Other
2: Staff
3: Board
4: Media

**Comment by d4mation** [comment]
I've created a new branch of this and some other minor display adjustments called `minor-display-adjustments`.

Currently only these changes are in there, but it looks like I'll be including #23, #20, #19, and #16 in that branch as well. That way we can get that all stomped out at once 👍
