### ISSUE TITLE
Big one - required - Boilerplates.  A big thing we missed.

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#24]
We missed a biggie.  But it's understandable.

First off, the Press Releases (er Media Releases soon?) on the website do not have the bolierplate.  But the Word Docs and Emails to media/staff/board do.

The boilerplate is a standard part of most any press release.  It's the basic info about the organization sending the press release.  You have probably noticed, on corporate ones, it always has the stock name and ticker ID.

Ours is:

> The Detroit Zoological Society – a nonprofit organization that operates the Detroit Zoo and Belle Isle Nature Zoo – is recognized as a leader in conservation, animal welfare and sustainability as well as providing sanctuary for animals in need of rescue.  With an annual regional economic impact of more than $100 million, the Detroit Zoo in Royal Oak is one of Michigan’s largest paid family attractions, hosting more than 1.4 million visitors annually.  Its 125 acres of award-winning naturalistic habitats are home to 2,400 animals representing 255 species.  In recognition of its environmental leadership, the Detroit Zoo received the top Green Award from the Association of Zoos & Aquariums, and was named Best-Managed Nonprofit by Crain’s Detroit Business.  The Belle Isle Nature Zoo sits on a 5-acre site surrounded by undisturbed forested wetlands on Belle Isle State Park in Detroit and provides year-round educational, recreational and environmental conservation opportunities for the community.  For hours, prices, directions and other information, call 248-541-5717 or visit www.detroitzoo.org. 

Sidenote, it's actually cool of Patricia/Jennie and I that the boilerplate is not on the site.  I explained way back, why in the CONTEXT of being on the website it's not really needed, and they agreed!

SO.  This needs to be inserted to the end of the post_content on each email.  Is this hard?  

My ideal would be for their to be an interface under global settings where this resides.  It needs to be a full-html, or at least able to add hyperlinks.  The idea is boilerplate does evolve over time, and the newest current version will always live here and the most up-to-date version will be slipped into the end of Media Release Emails.

Thoughts?

**Comment by d4mation** [comment]
This would be really simple to do, actually. I like the idea of making it an editable field within the Global Settings as well :+1:

**Comment by thisisjoewells** [comment]
Great!  I was hoping that it was fairly simple and my idea made sense!

**Comment by d4mation** [comment]
To clarify, you're wanting it appended to the Post Content or would it be better to have it in a separate section below the buttons?

It can be added below the buttons if needed, it would just mean that I have to edit the Raw HTML of the MailChimp Templates so I can pass another field in.

![image](https://cloud.githubusercontent.com/assets/7770631/18761335/7cbeac6e-80d2-11e6-9e54-240e52295911.png)

**Comment by thisisjoewells** [comment]
This is working well.  How you have it now is right, 'transparently appended', is what we do now.  I'm nearly certain this is what we/they want.  I'll confirm.  

Great work!

**Comment by thisisjoewells** [comment]
I still have not heard back, but I know this is good to go.  I'll close it, and just re-open if by some unexpected happenstance I was not right.
