### ISSUE TITLE
Sub-Footer Customization - where is this setting hiding!?

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#26]
Hi.

Among the minor edits from Patricia for the email template are to UN-italicize the "why did I get this?" message that MailChimp puts below the footer in the email.

![mailchimp-footer-cant-change1](https://cloud.githubusercontent.com/assets/9747248/18962114/7ee161d8-863d-11e6-87cb-c427dd9120be.png)

I have spent more time than I care to admit trying to figure out where to edit this thing.  It's killin' me.  Do y'all know where?  Is it a campaign setting, and thus generated in some API field I don't know how to access?

I also had to UN-capitalize the "add us to your address book" message.  This was a pain, and I had to do an over-ride similar to one needed if you want to translate the message by going from:

`*|HTML:LIST_ADDRESS_HTML|*`

To:

`*|LIST:ADDRESS|* <a href="*|LIST:ADDRESS_VCARD_HREF|*" >add us to your address book</a>`

Does anyone know how to do something similar for this sub-sub footer thing.  I can't find a merge-tag or even any place in the email template that controls this.  Ugg...

I am going thru detailed evaluation and testing of the system.  It's great work guys!  Good work @d4mation

**Comment by d4mation** [comment]
I looked through the settings a bit and that may be something that's a part of MailChimp itself and cannot be directly changed. It isn't a part of the Template and it seems it is something that MailChimp always appends to a Campaign.

It may be possible to add some CSS to the Template that will un-italicize that text, but given how finicky E-Mail HTML/CSS can be I'm not sure what type of success we'd have.

**Comment by thisisjoewells** [comment]
I am arriving at the same conclusion, that it's somehow baked-in at system level, and that maybe we could use CSS.  But that's not to reliable with email clients and the fact we have to use very-old safe code.

Here is the code for it.  I did a view source from Outlook.   There seem to be some issues perhaps with how the copy/paste of the view source came over.  Notice the wierd "s=tyle=" I will see what I can do with adding some CSS to template.  I'm not even sure we have a good class or ID to 'hook' on to:

`<a href=3D"http://detroitzoo.us1.list-manage.com/about?u=3D54d0adb3d70d603278d1=

09065&amp;id=3D7bdaef8845&amp;e=3D1ce7c721a5&amp;c=3Df54f2c74da" target=3D"_blank" s=
tyle=3D"color:#404040 !important;"><em>why did I get this?</em></a>`

Maybe this should read:

```
<a href=3D"http://detroitzoo.us1.list-manage.com/about?u=3D54d0adb3d70d603278d1
09065&amp;id=3D7bdaef8845&amp;e=3D1ce7c721a5&amp;c=3Df54f2c74da" target=3D"_blank" style=3D"color:#404040 !important;"><em>why did I get this?</em></a>
```

**Comment by thisisjoewells** [comment]
I think we are toast on this.  Since the <em>'s are hard-coded?

I did try adding these two (was being over-kill on syntax) commands to the CSS:

```
.3D{
color:#ff00ff !important;
font-style:normal !important;
}
3D{
color:#ff00ff !important;
font-style:normal !important;
}
```

I does not change anything.

I will submit the email template for approval, and note that this may not be possible.  I will suggest it's not worth over-thinking and over-worrying about and that MailChimp, a highly successful and sought-after company must have arrived at it as a good UX pratice after much thought and testing.

I'll let y'all know what they say.
