### ISSUE TITLE
Crazyness Avoided? - Sending certain press releases to a 4th list

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#27]
Hello team.

This week a new slightly crazy request was added to the PR-SOS.  I have carefully waited while leadership discusses it, thought through the implications, and come up with a better way.  (I think?)  We will see what develops.

I wanted to summarize it here, and also put the email chain in.

SUMMARY:
All the sudden folks here are thinking they want to send Press Releases to a list called RC (Renaissance Circle) which is a group of committed donors.  Many RC members are also on the board.  You are already seeing the first problem.

But the challenge is they only want RC to get certain Press Releases, not too often, and not if the Development folks think they would not be interested in the topic.  Great, now we have introduced curating to a system built for automation.  I have suggested that these are two different tasks, and that we should not shoe-horn the new task into the PR-SOS system, but rather add some new interface for sending RC emails if deemed appropriate.

Thoughts?

-----

# Here is my email where I try to change the direction of this slightly ill-conceived plan of theirs, you can infer the rest:

## Subject: Re: press releases for RC members

Hello all.
 
A share button or buttons are easy to do on any Press Release email whether it’s going to the Media, DZS-Staff, DZS-Board, or RC members.  I just need to work with y’all on the specifics.
 
I would like to make the case that we should either:
 
1.     Lump the RC members in with the DZS Board, and send them **all** Press Releases, or
2.     Do not include this functionality in soon-to-be launched Press Release SOS (WordPress system), but in a small add-on
 
Please hear me out.
 
1.     Patricia said there is overlap with the Board and RC members.  Sommer mentioned ways that we want to ‘regulate’ how may emails are sent to RC.  This is a mistake waiting to happen.  If there is an RC list and a Board list with overlap, then these people whom you do not want to overwhelm with emails will get the exact opposite: multiple copies of the same email.  That’s no good.
2.     Manually managing and removing these duplicates from any overlap is counter-productive and goes against the original intent of the new Press Release system which is **automation**.
3.     If we need to regulate how may Press Releases emails RC members are getting (based on content, frequency and other factors) we just introduced what I will call ‘human curation tasks’ that need to be done by Development (probably Sommer).  Remember, the new Press Release system on WordPress is designed to simplify and automate PR/Comm’s routine tasks.  Now we are adding case-by-case human judgement to what is supposed to be automating routine tasks.  It may require a serious re-build of a system that is just about ready to launch.
 
If RC members need to get certain Press Release emails based on certain factors, I would suggest this is a completely separate task.  It should not be part of the soon-to-be launched Press Release SOS automation functionality we are building in WordPress.  These are two different things we are trying to do.
 
Good news! - - I would propose that we make an easy way for Sommer/Development to send Press Releases she sees fit (based on topic and frequency of emails that have recently been sent) to the RC list.  With just a button click or three.  It would be a pretty simple add-on to the new Press Release SOS system we are building for PR/Comm.  And it would better reflect the fact we are doing two different things here.
 
These are my thoughts.  Thanks for reading.  Please let me know what you think.
 
-Joe-

**Comment by d4mation** [comment]
I'm agreeing with just about all that you're saying here. Human judgment of whether or not to send to this additional list&mdash;that has overlap with another list that will probably always send&mash;does not sound good.

About the only solution I see is to manually remove those duplicates from the RC list (as much as it will suck, so that duplicate emails should never happen) and maybe repurpose the "Other" column for this list? It seems like a good use-case for that "Other" column that is already included since it is only really there for a separate Campaign Sending station with its own logs.

It wouldn't even necessarily need to be renamed, since all of these columns can have their settings changed per-PR and via the Global Defaults.

**Comment by thisisjoewells** [comment]
Hi.  Good thoughts.

I actually told Patricia before I sent that email to everyone that we could use the "Other" column and would just have to manage the RC list and remove duplicates.  I then told her I'd try to convince her and everyone that RC list should get all or nothing...and that I have a better plan B (in email above).

It gets even messier, I fear.  This "RC" list is maintained and links with all donations/giving in BlackBaud Raiser's Edge.  So the last thing we want to do is have to maintain a duplicate RC list in MailChimp that has to be both manually synced with the Raiser's Edge list AND pruned to make sure overlap with Board Members.  This is just a bad idea.

I have talked with my colleague in charge or Tickets and eCommerce.  He agrees with all we are saying here.  He thinks what should be done is that:
 - if Development Staff see a Press Release and think it's something good for RC, which is what they are saying basically
 - then the Development staff should just copy/paste and set up a quick Raiser's Edge email.  A semi-automated system for this would be developed.

The point stands, which is, in the end this RC thing is a completely separate, intentionally-manual process that should not be part of PR-SOS automation.  Ideally.  We'll see if we can convince them.

**Comment by d4mation** [comment]
Hm, I see. I didn't realize that this list originated from a completely separate service. That definitely makes manually pruning a MailChimp list for it very unappealing.

I've never heard of Raiser's Edge, but if it has some kind of public API it should be possible to send e-mails directly through that service rather than doing all kinds of manual export/import/pruning with MailChimp. But that would need to be a separate plugin as this codebase is pretty specific to MailChimp&mdash;Trying to shoehorn in another service could make things too complicated for the End User. It would probably need to be in a separate Meta Box on the Edit Screen.

**Comment by thisisjoewells** [comment]
You are lucky you've never heard of Raiser's Edge.  :)

It's pretty big in the non-profit world.  I hear that many folks don't like using it...but it's part of BlackBaud which is a Slightly-Microsofty-huge company that buys up lots of good software systems an then ruins them by having bad integration.  ('m being overly mean, this is just what co-workers say in frustrated moments).  I hope we don't have to get into using their API, but I'm sure they have one.  And I am sure they are nice hard-working folks.

Boss CJ says we are not messing with adding any sort of RC-list feature right now.

He agrees it is a completely other task, and is for sure 'scope creep'.  We continue on as we are.

We may add-on a MailChimp-integration-based feature for the RC-list, or figure something else out.  For now I am happily marking this Issue won't-fix!
