### ISSUE TITLE
Text Formatting Issue

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#28]
Man.  It's always something...

The PR-SOS works great out of the gate on Jedi-Live.  It was easy to paste in API key, and do basic configuration and testing.

I did notice this semi-big issue.  We never noticed before because we never ad a title with a colon in it?

Title is - - Cool Drink of Water on Tap at 'Run Wild for the Detroit Zoo'

Something get's a bit mixed up in the API transfer?  Character encode issue?

![press-release-sos-character-issue1](https://cloud.githubusercontent.com/assets/9747248/19250243/63889cc6-8f07-11e6-904c-5f903c050555.png)

**Comment by d4mation** [comment]
This is really strange. It seems to only effect single-quotes.

I converted them to HTML Entities just now as a test and they stayed decoded (`&#039;`, prepended by an escaping slash) in the Campaign Subject. The other times are within the Campaign Body and if you look at the rest of the body copy, double-quotes work just fine.

**Comment by d4mation** [comment]
Although, it DOES effect double-quotes if they are in the Subject Line. It only ignores them if they are within the Body Copy "Proper" rather than just existing within the Template.

Very odd. I'll have to look into this more closely.

**Comment by d4mation** [comment]
Just pushed some code to Live that seems to fix this problem. Can you confirm when you get the chance?

**Comment by thisisjoewells** [comment]
We are mostly there.  Testing just now (at conference):

- Full quotes in subject lines go thru fine
- Full quotes in body copy are fine
- Single quotes (apostrophes?) in subject line are fine
- Single quotes (apostrophes?) in body copy - **SAME ISSUE we were having**

See this press release in which I added single-quote apostrophes (and need to remove ASAP):

>>Amphibiville Searching for a "Newt" Leader<<

Line towards bottom about National Amphibian Conservation Center.

The fix just needs to be applied for body copy too?

![press-release-sos-character-issue2](https://cloud.githubusercontent.com/assets/9747248/19357367/4fae3c94-913f-11e6-96f8-93385fa3fa72.png)

**Comment by d4mation** [comment]
I believe I've got it this time. I applied the fix to any data that comes from the Form, so it should work fine now! I tested it with the same Media Release from your screenshot just now and it looks good.

![image](https://cloud.githubusercontent.com/assets/7770631/19366502/578c4de0-9165-11e6-8781-12dee15b8001.png)

**Comment by thisisjoewells** [comment]
We forgot to close this.  Good work on the fix.
