### ISSUE TITLE
Blast.  'One Last Change' - Multiple Boilerplate Option needed...

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#30]
A miscommunication/misunderstanding was uncovered at today's PR-SOS would-be Training and Launch Meeting.

It's with the Boilerplate.

Instead of having one Boilerplate on the Global settings, we need 3 stock boilerplates:
- Boilerplate 1 - Default DZ
- Boilerplate 2 - BINZ
- Boilerplate 3 - Custom

Then on Global Settings we need a drop down each group where the default biolerplate can be specified.  Bonus, can we put horizontal rules between each group to make it easier to keep them separated mentally?

Then on the actual press release pages, in Distribution box, the 4 columns need to be able to have a default Boilerplate selected, just like list and template. 

One last bonus request as part of this.  Can we make the code block where the 3 boilerplates are added/specified/controlled in the code be commented and easy to dupilcate in case 1 more is needed in like a year?
## Background Info:

The boilerplate needs to be on the Press Release Emails, but not on the website posts.  Up until now, they have just copy/pasted the Boilerplate in manually to emails, and left it off the website post.

This is why any mention of boilerplate flew under the radar, and was not addressed until the 9/21 'prototype review' meeting with Patricia and Jennie (end users).

You'll remember that issue #24 added in the request for a global Boilerplate setting.  This is good, but there are enough exceptions to the rule that we need more options.  For Belle Isle Press Releases (perhaps 5% of press releases) and special/targeted press releases (about 7%).

**Comment by d4mation** [comment]
Just added a commit to a new `issue/30/multi-boilerplate` branch that should address this. 

I'm going to look into if there's a way to put horizontal rules between the defaults for each section. I agree that especially now that is difficult to look through on the Global Defaults page.

As far as adding new Boilerplates goes, it is pretty simple! Here's a snippet as an example:

```
add_filter( 'dzs_mailchimp_boilerplates', 'add_new_boilerplate' );
function add_new_boilerplate( $boilerplates ) {

    $boilerplates[ 'some_new_boilerplate' ] = 'Some New Label';

    return $boilerplates;

}
```

This would add a new Boilerplate called "Some New Label" with a database option key of `_rbm_dzs_mailchimp_some_new_boilerplate`. It could then be grabbed at any time using `get_option( '_rbm_dzs_mailchimp_some_new_boilerplate' )` if you needed to.

**Comment by d4mation** [comment]
Got some horizontal rules in there with some minor tweaking 👍 

![image](https://cloud.githubusercontent.com/assets/7770631/19743274/aa67f13c-9b96-11e6-849f-400b047b234b.png)

**Comment by thisisjoewells** [comment]
I don't see the horizontal lines.  But we know that's DZS-caching oddity.  Testing on staging looks great.  The screenshot with horizontal lines knocks it out of the park.

Let's just push to Jedi-live!  Perhaps we can still get this out the door in the month of October as planned.

Thanks for working so fast on it!

**Comment by d4mation** [comment]
Just merged to `master` and pushed to Jedi-Live 👍 

I saw the lines on Staging but not on Live. The HTML Classes necessary are there so my guess is the CSS is cached. It should resolve itself after a while is my guess similar to the thing where the 4 Columns weren't showing up for you below the Content before.

All the default Boilerplates are set to `Default DZ` since I didn't know what you wanted them set to, but otherwise it should be good to go!

**Comment by thisisjoewells** [comment]
Shoot.  I was testing today, and I can't get the other two boilerplates to show up in email templates.  Are we sure we pushed _everything_ to Jedi-Live?

I am doing some methodical tests and will report back...

**Comment by d4mation** [comment]
My only guess is that maybe the JavaScript on the Edit Screen is cached for you currently. It has to pass the Boilerplate Name to PHP via JavaScript to grab the correct one from the Database. It could just be grabbing the old one (which is identical to the Default boilerplate) as a result.

Are you able to see the lines on the Global Settings page yet? That could indicate whether things are still cached for you.

**Comment by d4mation** [comment]
Just ran a quick test on Jedi-Live (Since we've got that Caching Phantom Menace there) and I believe this is the case. I sent this one to myself using the BINZ Boilerplate:

![image](https://cloud.githubusercontent.com/assets/7770631/19945120/168cbbee-a115-11e6-9d35-62431745e5d2.png)

**Comment by thisisjoewells** [comment]
Yes.  Something seems amiss.

I tried each boilerplate (Default DZ, BINZ, Custom) and _none_ show up.

To corroborate, I sent the exact same email (Press Release on live: "Detroit Zoo Heats Up for Wild Summer Nights".  

On 10/26 before the change Boilerplate is there.   Today under exact same circumstances and settings _no_ boilerplate.

Further testing.  Sent one on Padawan-Staging, and it works fine.

**Comment by thisisjoewells** [comment]
Hi @d4mation.  I didn't see your comment before my last one...

I didn't think to try it on my phone, understandably, via cell-phone data to be off DZ-network.  Since this is not easy with phone.

You are right, based on your test....it's likely the Phantom Menace again.  Man!!!

Will try clearing CloudFlare and WP-Engine.

**Comment by thisisjoewells** [comment]
Caching will be the end of me...

After clearing CloudFlare cache, the here-to-fore non-existent horizontal lines on the M Settings page are now there.  BUT the email still is not passing it.

Caching is still the most likely issue.  Let me try it in a full cache-cleared browser.

**Comment by thisisjoewells** [comment]
Ok.  It must be Phantom-menace caching.  It works after clearing WPE cache, CloudFlare, and browser from beginning of time :)

I suppose one problem is that have it in my head that anything on WP-Engine that is /wp-admin is not cached.  But this is inaccurate or oversimplified I suppose.

I'll mark this as closed, but...  Let me first jot down what I think are the caching variables.  If one of you wants to correct me if I am wrong, or note which types of files and functions are at play in each of the three caching places, feel free to.  I may write some internal documentation on it.

I don't want to be on vacation some day and have co-workers panicking.

## The 3 Caching Factors on DZ-Multi-Site:

1 - WP-Engine cache
May cache php, css, JS,
Does not cache content or images

2 - CloudFlare cache
May cache php, css, JS,
May rarely cache images
Does not cache content

3 - Local web broswer cache
May cache php, css, JS,
Does not cache content or images
