### ISSUE TITLE
Change Media Kit button label

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#31]
They have requested the Media Kit button be changed to 'Images' from 'Media Kit (Photos and Video)' since often we may only have one or the other...

Let me see if I can swing this.  I'll make a branch and what-not.

**Comment by d4mation** [comment]
Handled in #32.

**Comment by thisisjoewells** [comment]
I'm gonna re-open this for a change requested today, since it's so similar.

They have requested the Word/PDF button go from "Download Story" to "Download Press Release".  It's mildly frustrating they didn't make this change in the last 3 months while I was asking them to review the templates.

**Comment by thisisjoewells** [comment]
Handled in pull request #35
