### ISSUE TITLE
More changes after 11/4 'training' meeting

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#33]
I met today with Patricia and Jennie to train them on using the PR-SOS.

They noticed _new_ changes to the email templates.  I should be able to handle these.  I'm glad I got the email templates into this repo and under version-control.

Changes:
- Email should be from Patricia _not_ Detroit Zoological Society.  
- Subject line ends up in the email twice, because of how we use the 'gray box' are that has MC:Subject and 'View this email in a browser'.  They want this entirely removed.  I will think thru ramifications and do that
- The PDF/Word Button that says 'Download Story' needs to say 'Download Press Release', which will also require tweaking the button width settings so the two buttons are the same width
- Also on Microsoft Outlook 2016 - the button text appears to disappear if you have clicked on the link already, this is because there must be a default visited-link color that closely resembles the violet color of our button, this does not happen on Mac or iOS

**Comment by d4mation** [comment]
> Email should be from Patricia not Detroit Zoological Society.

That should be something that can be handled via the Global Default Settings, so you won't have to touch the code for this at all. 👍 

> Also on Microsoft Outlook 2016 - the button text appears to disappear if you have clicked on the link already, this is because there must be a default visited-link color that closely resembles the violet color of our button, this does not happen on Mac or iOS

The `:visited` pseudo-selector should be able to handle that I think. It can't go into the `style` attribute of the button, but if it were thrown into a `<style type="text/css"></style>` block somewhere it ought to work. That's an unfortunate little bug though. I know that button was originally generated via MailChimp's Template builder so you'd think they'd account for that 🙃

**Comment by thisisjoewells** [comment]
Update on these changes:


- Can be done in global settings or will change with #36 - Email should be from Patricia not Detroit Zoological Society.
- Working on best possible fix with #34 - Subject line ends up in the email twice, because of how we use the 'gray box' are that has MC:Subject and 'View this email in a browser'. They want this entirely removed. I will think thru ramifications and do that
- Done with changes to MailChimp templates.  ~~The PDF/Word Button that says 'Download Story' needs to say 'Download Press Release', which will also require tweaking the button width settings so the two buttons are the same width~~
- Done with a:visited p-selector in template. ~~Also on Microsoft Outlook 2016 - the button text appears to disappear if you have clicked on the link already, this is because there must be a default visited-link color that closely resembles the violet color of our button, this does not happen on Mac or iOS~~

I will close this as there are other issues open for the open items on the bullet list.
