### ISSUE TITLE
False 'Not Sent' Message.

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#38]
When we sent out first PR-SOS-sent Press Release today we were excited.

But after the success messages, there was a green 'Not Sent' message.

I checked and the MailChimp Campaigns went out just fine.  Probably a miscommunication with the API?

(we discussed this on Slack, @d4mation probably has the fixed found and in progress)

**Comment by d4mation** [comment]
This should be fixed on Jedi-Live. I merged the fix into `master` in 109becd.

**Comment by thisisjoewells** [comment]
Slightly condensed Slack conversation:

----
## Joe Wells	[10:49 AM]  
So the oddity.

When Patricia was nervously drafting, publishing and doing the Distribution on this her _first ever WordPress post_ (crazy-cool!  she always had others do that stuff) - after hitting send:

- We got the ‘Campaign Sent Successfully’ message
- Then the green status text load below with ‘sent from on, by, etc’
- BUT THEN another green status line of text comes up ‘Not Sent’.  But I check MailChimp and the campaign went fine.  So there is some API mis-communication error?

## Eric Defore	[10:54 AM]  
Huh, that’s weird. I never encountered that...

## Joe Wells	[10:54 AM]  
Yes.  We’ve never sent to more than a few addresses at a time.  And it’s hard to make a big ol’ list of tests...

[10:55]  
If I had to wager a guess…it’s that MailChimp sends them out over a set amount of time.  And the API get’s back something like ‘Yep, I’m doing it’, but then tells WordPress ‘Not sent’ just because we need to hone in on something (?)

[10:56]  
The ‘Not Sent’ came up like 25 seconds after. (edited)

[10:57]  
BEAR IN MIND - I’m monitoring the campaign stats on MailChimp.  They did or are going out fine.  So this is not major issue. (edited)

## Eric Defore	[10:57 AM]  
I’m going to play around with it. That “Not Sent” I believe is the default “There’s No Log Yet” text. I’m not sure why it is disappearing and then reappearing.

## Joe Wells	[10:58 AM]  
Ah yes.  True.  It is disappearing.  It’s not there at this exact moment when I checked...

[10:58]  
It’s not on the View All Posts screen ever, I don’t think.

## Eric Defore	[11:00 AM]  
uploaded an image: Pasted image at 2016-11-17, 11:00 AM 
Add Comment

## Eric Defore	[11:00 AM]  
I found the one that Patricia sent too and it isn’t showing the `Not Sent` text _anymore_.

I think it is probably something weird in the JavaScript

## Joe Wells	[11:00 AM]  
We’ve never sent the Glice one.

## Eric Defore	[11:01 AM]  
Yeah, you said it is not on the “View All Posts” screen so I checked because I thought that was weird.

## Joe Wells	[11:01 AM]  
The ‘Not Sent’ in question was _green_ and only on the actual Press Release page....

[11:02]  
And it was _in addition_ to the ‘Sent on…’ message, and also we now see comes and goes...

[11:02]  
So I think you and I are on the right path.

## Eric Defore	[11:02 AM]  
Yep, it is a JS bug. Found it. I’ll get that fixed.

## Joe Wells	[11:03 AM]  
@kyle - @d4mation - IF Y’ALL have other urgent stuff with other clients today....by all means....we are OK for today....

[11:03]  
Overall - Success!!!!

[11:03]  
And cool!!  If you can find and fix fast!

## Eric Defore	[11:07 AM]  
Fixed :ok_hand:

Eric Defore	[11:14 AM]  
Since I had to modify the JavaScript, my guess is the whole caching bug will be at play. Probably will have to purge CloudFlare and whatever else.
