### ISSUE TITLE
Problem - Templates missing from drop-down

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#39]
Man.  Our bad luck.

We went to send the 2nd-ever PR-SOS under urgent timing last Friday.  And there was an issue.  Not a world-ender.

2 of the templates were missing from the drop-down selector for template on both the per-post 'Distribution' interface and the Mailchimp Settings.

As a one-time work-around we just put a link to the Google Drive collection of images in the body copy of the site.

![pr-sos-missing-templates-issue1](https://cloud.githubusercontent.com/assets/9747248/20893207/f7af0df6-bade-11e6-81e7-09d1a5517a1a.jpg)

I am wondering, if this is perhaps on me?  Maybe when I was customizing the HTML templates for button color, pre-header formatting and other tweaks...I overwrote a key line needed for the API to identify it.  This seems most likely place too look.  I'll look into this, but also wanted to get this officially posted.

**Comment by d4mation** [comment]
MailChimp seems to do this dumb thing where it includes a bunch of what I assume are default templates in the API response but they don't show up within your own list of Templates when you're logged into MailChimp.

The API response is limited to 10, and it would appear that our Templates are numbers 9, 10, 11, and 12 in the list so the other 2 get cut off.

I'll have to make a Loop of sorts to continue to query with an offset until it returns less than 10 Templates I think to help ensure that we're pulling all the ones we want.

**Comment by d4mation** [comment]
Just pushed a new branch which I believe should address this. I found a way to restrict the Query to only User-Created Templates and from there I also added a loop which _should_ grab any others if the number of User-Created Templates goes over 10.

**Comment by thisisjoewells** [comment]
Is the branch on Padawan-Staging right now?  I can't find the branch when I go to switch:

![no-other-mc-plugin-branches](https://cloud.githubusercontent.com/assets/9747248/20939885/ac4da954-bbbe-11e6-99de-dc09bebab351.jpg)

I fear it is the 'Phantom Menace' DZS-Network oddities?

**Comment by d4mation** [comment]
Ok, that's really weird. It has Branch Switching enabled so I don't know why it is trying to use Versioning rather than Branches.

I'll go ahead and SFTP the changes on to Staging.

**Comment by d4mation** [comment]
I have no idea what happened there, but I just SFTP'd in the correct branch and now Branch Switching seems to work again 🙃 

Should be good for you to test now on Staging.

**Comment by thisisjoewells** [comment]
This looks good on Padawan-Staging.  Feel free to push to live when you are able.
