### ISSUE TITLE
Possible new feature request - No boilerplate option...

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#40]
The never ending saga of the Boilerplate continues...

When we were sending the 2nd-ever PR-SOS Press Release on Friday 12/2/16 - they decided they did not want a Boilerplate in this case.

I made clear, this was never requested, but I could make it happen.  

My end-users said they have requested this, however I can prove in my notes it was never requested.  It's a bit frustrating to have new features requested each time I talk with your end-users in person :)  Especially when the tone of the request is a little bit like 'why isn't this there, you dummy', when in reality it was never requested.  Anyway...

The workaround for this case/incident was to use the new Custom Boilerplate option, and to leave the Custom Boilerplate field empty.  Worked fine.

I think I may make a template that does not pull in a bullet point, just because this is a better UI and UX. I'll assign to me and let you know if I need any help from you smart folks at RBM.

**Comment by d4mation** [comment]
In the case of the Boilerplate it actually doesn't have its own place in the Template, so a new Template (currently) wouldn't solve the problem.

What could possibly be done is modify `get_boilerplates()` in `core/admin/class-dzs-mailchimp-admin.php` to include a "No Boilerplate" option and have it not append the Boilerplate to the Campaign Content if that value is present in the `POST` request.

Or, the Boilerplate could be passed as a custom API parameter similar to most things for these campaigns. However, that would mean that each Template would need to be modified for that on top of a new one being created.

**Comment by thisisjoewells** [comment]
I guess the first option is the most versatile?

Would there just be a check-box for 'Don't Include Boilerplate' on the back-end UI?

That would work.

**Comment by d4mation** [comment]
It could be a checkbox, but I believe that would end up being ultimately more confusing for the User since now you have _two_ fields pertaining to the Boilerplate. Adding it as a separate option in the Dropdown would make it more clear that "No Boilerplate" has been chosen.

It ends up being a bit more versatile, cleaner, and a bit quicker to implement to boot :\^)

**Comment by thisisjoewells** [comment]
Oh.  Yes.  Yes.  Of course it would be better in the dropdown.  Another check-box _would_ be confusing.

I didn't understand that as the option of how the _omission of value_ would be administered via the UI.

A drop-down with DZ, BINZ, Custom, None would be excellent.  Please do-that.

Now I will go stare at the PR-SOS for twenty minutes and try to guess every possible 'why doesn't it do this?' future enhanced feature request they can throw at us next time.  :)

**Comment by d4mation** [comment]
Just pushed a new branch with these changes. If you refresh the GitHub Updater Transients on Staging it _should_ pull in the new branch properly now.

**Comment by thisisjoewells** [comment]
Looks great.  Drop-down works.  Test email has no boilerplate when 'None' selected.  Great work.  Thanks.

This feature is ready to be a Jedi.
