### ISSUE TITLE
Settings for from and reply to

### ISSUE THREAD

**Issue by brashrebel** [TheDetroitZoo/pr-mailchimp-integration#7]
Just wondering: do we really need these global settings? I don't think they'll ever need to be changed inside WP and it might make sense to just use what exists in MailChimp as the defaults for the lists.

**Comment by d4mation** [comment]
Actually, as dumb as it sounds, we do need to define these. 

Unless there's an API Endpoint to grab a global MailChimp default, these settings are defined separately for each Campaign you send out and as far as the API is concerned, they are more likely to be different.

[POST /campaign Documentation](http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/)

If you expand the "Settings" section, you'll see that those are actually required fields as part of the POST Request.

**Comment by thisisjoewells** [comment]
Actually this could be really useful.

I never thought about it, but most Press Releases say to respond to Patricia with questions.  But then sometimes it's to Jennie (mostly when Patricia is out of town, but sometimes when it's something Jennie is more knowledgeable on).

They might want to be able to choose the sender on a case-by-case basis.  I never thought about it until now.

If that does have to be defined on a campaign-by-campaign basis, maybe we make it a setting on the post, and not on a global settings pane.

If this is difficult, it could be a future iteration.

**Comment by d4mation** [comment]
I could set it up so that there's the Global "Defaults" and they could be overridden on a Post-By-Post basis. How does that sound? I think that's the best of both worlds.

I could set it so that the Defaults show as Placeholders in the Text Fields on the Posts as well so that it is more obvious that the field doesn't _have_ to be filled in.

**Comment by brashrebel** [comment]
I like that last idea.

**Comment by d4mation** [comment]
I just pushed a change to Padawan-Staging that includes fields for overriding the Default From Name and Reply-To address. I tested it on my end and it appears to work as expected. 👍 

![image](https://cloud.githubusercontent.com/assets/7770631/18529424/feb4113e-7a9a-11e6-900b-c0d49e637133.png)
