### ISSUE TITLE
Status Indicators on Press Release list page

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#9]
It would be a pretty good UX and useful UI if we could list the 'sent' status of each Press Release when you are on the list of Press Releases on the back-end.

Imagine if the default view was:

Title - Published: status/date - Sent to media: status/date - Sent to staff: status/date - Sent to board: status/date

It would be a nice confirmation that everything is done, and a way to keep track of status when PR department is doing complex timing of the release.

Thoughts?

**Comment by d4mation** [comment]
Currently it shows a log beneath the "Send Campaign" button with everything here with the exception of showing the "Sent Status". 

Granted all of my testing was to a List that only contained myself, but the Sending of the Campaign seemed pretty instantaneous. I'd have to refresh the Campaigns list on MailChimp pretty quickly to catch it before it finished sending. There's an API Endpoint that can check the Sent Status of a Campaign, but it may finish sending before the Response gets returned to the Server to be honest, haha.

It sounds like you're thinking to show the log directly beneath the Post Title though? That should be able to be accomplished.

![image](https://cloud.githubusercontent.com/assets/7770631/18527370/7a577e2e-7a92-11e6-96ae-5c45da8c2a98.png)

**Comment by thisisjoewells** [comment]
Cooool.  It will be great to have this info shown there on each post.

No, what I meant and was thinking it would be really nice to see it on the Press Release listing page on back-end.  One of the columns.  What's the official term for this, here:

http://dzs2.staging.wpengine.com/wp-admin/edit.php?post_type=press-release

You know to allow quick glance at the history of all Press Releases.  I makes it more of an enterprise-class tool.  All info about press releases would live on the WordPress site, the press release, and info on when they were sent and to whom...

**Comment by d4mation** [comment]
Oh, I see what you're saying. You want to see the Log on that page as well within a Column? That should be very possible and it's a very good idea 👍

**Comment by thisisjoewells** [comment]
That looks good!
